package entities;
// default package
// Generated Oct 19, 2018 3:10:04 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Remail generated by hbm2java
 */
@Entity
@Table(name = "REMAIL", catalog = "MYREMINDER")
public class Remail implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "customer_id", unique = true)
	private String emailId;
	private String sender;
	private String recipients;
	private String subject;
	private String header;
	private String footer;
	private String contents;

	public Remail() {
	}

	public Remail(String emailId, String sender, String recipients,
			String subject, String header, String footer, String contents) {
		this.emailId = emailId;
		this.sender = sender;
		this.recipients = recipients;
		this.subject = subject;
		this.header = header;
		this.footer = footer;
		this.contents = contents;
	}

	@Id
	@Column(name = "email_id", unique = true, nullable = false, length = 50)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "sender", nullable = false, length = 50)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "recipients", nullable = false, length = 50)
	public String getRecipients() {
		return this.recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	@Column(name = "subject", nullable = false, length = 50)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "header", nullable = false, length = 50)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "footer", nullable = false, length = 50)
	public String getFooter() {
		return this.footer;
	}

	public void setFooter(String footer) {
		this.footer = footer;
	}

	@Column(name = "contents", nullable = false)
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

}
