package com.nana.entities;
// default package
// Generated Oct 19, 2018 10:53:25 AM by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Rdivision generated by hbm2java
 */
@Entity
@Table(name = "RDIVISION", catalog = "MYREMINDER")
public class Rdivision implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(generator="system-uuid")
	@GenericGenerator(name="system-uuid", strategy = "uuid")
	@Column(name = "division_id", unique = true)
	private String divisionId;
	private String divisionName;

	public Rdivision() {
	}

	public Rdivision(String divisionId, String divisionName) {
		this.divisionId = divisionId;
		this.divisionName = divisionName;
	}

	@Id
	@Column(name = "division_id", unique = true, nullable = false, length = 50)
	public String getDivisionId() {
		return this.divisionId;
	}

	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}

	@Column(name = "division_name", nullable = false, length = 50)
	public String getDivisionName() {
		return this.divisionName;
	}

	public void setDivisionName(String divisionName) {
		this.divisionName = divisionName;
	}

}
